---
kind: "Deployment"
apiVersion: "apps/v1"
metadata:
  name: {{ mustToJson .Release.Name }}
  labels:
    component: {{ mustToJson .Release.Name }}
spec:
  replicas: {{ mustToJson .Values.replicas }}
  selector:
    matchLabels:
      component: {{ mustToJson .Release.Name }}
  template:
    metadata:
      labels:
        component: {{ mustToJson .Release.Name }}
    spec:
      {{ if .Values.architecture }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - {{ mustToJson .Values.architecture }}
      {{ end }}
      containers:
        - name: {{ mustToJson .Release.Name }}
          image: {{ mustToJson .Values.image }}
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: {{ mustToJson .Values.cpu }}
              memory: {{ mustToJson .Values.memory }}
            limits:
              cpu: {{ mustToJson .Values.cpu }}
              memory: {{ mustToJson .Values.memory }}
          ports:
            - containerPort: {{ mustToJson .Values.port }}
---
kind: "Service"
apiVersion: "v1"
metadata:
  name: {{ mustToJson .Release.Name }}
  labels:
    component: {{ mustToJson .Release.Name }}
spec:
  selector:
    component: {{ mustToJson .Release.Name }}
  ports:
    - port: 80
      targetPort: {{ mustToJson .Values.port }}
---
apiVersion: "gateway.networking.k8s.io/v1"
kind: "HTTPRoute"
metadata:
  name: {{ mustToJson .Release.Name }}
  labels:
    component: {{ mustToJson .Release.Name }}
spec:
  parentRefs:
    - name: "public"
      namespace: "kube-system"
      sectionName: "https"
  hostnames:
    - {{ mustToJson (print .Release.Name ".platform-dev.reainternal.net") }}
  rules:
    - backendRefs:
        - name: {{ mustToJson .Release.Name }}
          port: 80
